### ISSUE TITLE
Text and clock are partly cut off

### ISSUE THREAD

**Issue by janequichocho** [breakbreakdown/webapp#10]
Some of the text and part of the clock under "Time left in day" are cut off by the circle icon on the main screen.

![cut-off-text](https://user-images.githubusercontent.com/35388572/40903841-aaa29d86-678d-11e8-9a44-6b788dbb1263.JPG)

**Comment by juania1-1529573** [comment]
We might have different window sizes, will prioritize other bugs before we reach this one. Duplicate
