### ISSUE TITLE
Can add events with time conflicts

### ISSUE THREAD

**Issue by janequichocho** [breakbreakdown/webapp#11]
I am able to add two events at two different locations that occur at the same time.

Reproduction Steps:
1. Log In
2. Click on + Icon in "Add Event" Section
3. Add an Event with the following information
    - Title: Party 1
    - Date: June 4, 2018, 12pm - 2pm
    - Location: Red Square
4. Click on Add to Calendar, the event will add successfully
5. Click on Cancel
6. Click on + Icon in "Add Event" Section
7. Add an Event with the following information
     - Title: Party 2
     - Date: June 4, 2018, 12pm - 2pm
     - Location: The Quad
8. Click on Add to Calendar, the event will add successfully

**Comment by juania1-1529573** [comment]
Google Calendar allows this functionality, so we still wanted to give the users the option of allowing what Google Calendar allows as well. They allow for overlapping events to occur. Thanks!

**Comment by abegel** [comment]
But does the display properly avoid double-counting the overlapping time?
