### ISSUE TITLE
Can't change color of event

### ISSUE THREAD

**Issue by janequichocho** [breakbreakdown/webapp#13]
Reproduction steps:
1. Log in
2. Create an event occurring today from the + icon in the "Add Event" section, leave the color as the default color
3. Click on the circle icon and the event window will pop up
4. Click on "Edit"
5. Change the color to red

When I try these steps the color of the event will stay the same.

**Comment by aqt21** [comment]
Edit event has ended up out of our scope. However, changing color in add event has been fixed and should be able to add events of different colors
