### ISSUE TITLE
Sign In issue

### ISSUE THREAD

**Issue by AntonZheng** [breakbreakdown/webapp#14]
Pop up keeps asking me to sign in after the initial sign in.

![screen shot 2018-06-04 at 1 39 41 am](https://user-images.githubusercontent.com/16981362/40907294-3f81c864-6798-11e8-8635-cb3a3208b4e3.png)

**Comment by juania1-1529573** [comment]
The additional popups after sign in are for authorizing Google Calendar to use our project.
