### ISSUE TITLE
Events aren't being properly displayed

### ISSUE THREAD

**Issue by AntonZheng** [breakbreakdown/webapp#15]
Despite having two events on my calendar, they aren't displayed. After a couple refreshes and resigning in, events are sometimes populated.

![screen shot 2018-06-04 at 1 42 41 am](https://user-images.githubusercontent.com/16981362/40907413-9e1d8ee4-6798-11e8-863d-dddf242f999f.png)

**Comment by juania1-1529573** [comment]
Duplicate; out error was that if someone had a task in their day then it wouldn't push to firebase. Should be fixed by 5pm. Thanks!
