### ISSUE TITLE
Circle disappears when tasks ARE checked (incognito)

### ISSUE THREAD

**Issue by hmansoori** [breakbreakdown/webapp#18]
As a follow up to the other issue I filed, when I ran the app in an incognito session, the opposite issue happened. Now when I check off tasks or events after logging in, the circle disappears until I uncheck all items in the checklist.

**Comment by juania1-1529573** [comment]
We are unable to replicate this on our side, as we fix our other current bugs it might fix this issue.

**Comment by abegel** [comment]
@hmansoori Can you confirm that this bug is fixed?
