### ISSUE TITLE
After adding event, pop up box does not disappear

### ISSUE THREAD

**Issue by vaneshsu99** [breakbreakdown/webapp#19]
The add event box does not disappear after I add the event. I have to click cancel to close the box.

Reproduction steps:
1. Click on add event button
2. Click on add to calendar button
3. Click on ok button
4. Verify that add event box does not disappear

**Comment by nogawb** [comment]
This was a designed feature to allow users to easily input multiple events quickly. 
However, that is a user flow design problem and we will make changes to the user flow in future versions.
