### ISSUE TITLE
Logged into UW gmail on incognito mode but the site won't let me onto the home page and or let me try a different account

### ISSUE THREAD

**Issue by soobkwon** [breakbreakdown/webapp#21]
Keeps buffering onto the white verification page after I logged in with my UW gmail but the white box never loads and then sends me back to the app's welcome page again. However, when I first verified my email, it went back to the app's welcome page too. There was no way for me to change my gmail account either since the white box never loads. I even tried to restart the webpage but the white box never loaded. 

<img width="1280" alt="screen shot 2018-06-04 at 3 17 16 pm" src="https://user-images.githubusercontent.com/24904480/40944724-af55c470-680a-11e8-8787-7389eb2e8313.png">
<img width="1280" alt="screen shot 2018-06-04 at 3 17 12 pm" src="https://user-images.githubusercontent.com/24904480/40944725-af69614c-680a-11e8-81da-9cc47a321eab.png">
<img width="1280" alt="screen shot 2018-06-04 at 4 05 11 pm" src="https://user-images.githubusercontent.com/24904480/40946203-2ad647fe-6811-11e8-9587-5e9a04f8ef41.png">

**Comment by juania1-1529573** [comment]
Can not replicate this condition on our side

**Comment by abegel** [comment]
@soobkwon Can you check if you still get this bug?

**Comment by soobkwon** [comment]
@abegel I am still getting the same bug. I have re-entered my UW information to access my UW gmail and have even tried my other personal gmail accounts too and it still will not let me pass the sign-in page in incognito mode. However the regular window allows me to log in. I have even tried to restart the process by creating a new incognito window and signing-in again, but the same problem still occurs. 


Incognito Mode:
<img width="1280" alt="screen shot 2018-06-05 at 11 19 35 pm" src="https://user-images.githubusercontent.com/24904480/41020335-576983ce-6917-11e8-8ce9-9c707a701309.png">
<img width="1280" alt="screen shot 2018-06-05 at 11 19 54 pm" src="https://user-images.githubusercontent.com/24904480/41020334-5753cc96-6917-11e8-8014-21a6ad396166.png">
<img width="1280" alt="screen shot 2018-06-05 at 11 16 05 pm" src="https://user-images.githubusercontent.com/24904480/41020336-5781ea7c-6917-11e8-9e70-b0996c68c128.png">
<img width="1280" alt="screen shot 2018-06-05 at 11 20 11 pm" src="https://user-images.githubusercontent.com/24904480/41020331-57089a3c-6917-11e8-9ea6-627edcb0487b.png">

Regular Window:
<img width="1280" alt="screen shot 2018-06-05 at 11 25 08 pm" src="https://user-images.githubusercontent.com/24904480/41020437-bb10dab2-6917-11e8-8c87-4b88bf368125.png">

**Comment by abegel** [comment]
@juania1-1529573 Any thoughts?

**Comment by juania1-1529573** [comment]
Have you tried with a different browser, maybe Chrome?

**Comment by juania1-1529573** [comment]
Weird, I was able to log in through Safari with my UW account and I passed the login screen through UW.
<img width="1323" alt="screen shot 2018-06-06 at 10 15 03 pm" src="https://user-images.githubusercontent.com/15044607/41079586-341b3910-69d7-11e8-92d5-66e01e59d1c2.png">

**Comment by soobkwon** [comment]
@juania1-1529573 I just tried with Chrome and it works! Was your Safari on incognito mode? My UW account still does not work for Safari incognito mode.

**Comment by juania1-1529573** [comment]
Great!! My safari was not, maybe that's why.
