### ISSUE TITLE
After pressing the "settings" and then the "add event" button, the user is signed out.

### ISSUE THREAD

**Issue by rykerls** [breakbreakdown/webapp#22]
## Expected Behavior
The "add event" popup/dialog is displayed.

## Current Behavior
The user is taken to the `signin/` page and signed out of their account.

## Steps to Reproduce
1. Open https://aqt21.github.io/ in a Private/Incognito tab
2. Complete the sign in process and get taken to the BreakBreakdown dashboard/homepage.
3. Click on the Settings icon / arrow key. NOTE: There is no settings window shown, or any other observable change to the app when I click on this button.
4. Click on the "+" symbol in the "Add Event" section of the page.
5. The user is navigated back to the homepage and prompted to sign back in.

## Context (Environment)
I discovered this bug when I was trying to get a feel for what you can do in your app. At first, I was a bit confused why the settings/ arrow icon didn't seem to work in my browser. Then I went on to try and add an event, and was taken back to the sign in page. After signing back in and trying to reproduce it, it seems that it only demonstrates this behavior if you follow the steps above before doing anything else on the page. If you perform other actions on the page and then try this, it doesn't seem to work.

Browser: Chromium (on a desktop computer)

**Comment by juania1-1529573** [comment]
We changed the settings button to logout, but couldn't modify the Requirements after the due date freeze.
