### ISSUE TITLE
After Adding Event, the pop-up window stated that the event has been added to Google Calendar, but it does not show up in my Google Calendar

### ISSUE THREAD

**Issue by Jingwnpn** [breakbreakdown/webapp#3]
<img width="869" alt="screen shot 2018-06-03 at 6 51 07 pm" src="https://user-images.githubusercontent.com/22405025/40894556-6840984a-675f-11e8-95cc-c5a5d14bf740.png">
<img width="547" alt="screen shot 2018-06-03 at 6 51 25 pm" src="https://user-images.githubusercontent.com/22405025/40894558-69a552ac-675f-11e8-875e-8af89b7d5d00.png">

**Comment by nogawb** [comment]
We made changes so the add event should be working now.
