### ISSUE TITLE
There is no 'cancel' button

### ISSUE THREAD

**Issue by 5tigerjelly** [breakbreakdown/webapp#5]
![image](https://user-images.githubusercontent.com/15973528/40895373-e91f32b0-6763-11e8-8a86-53627c26ec68.png)
Alert box saids to click `cancel`, but there is only `OK` button

**Comment by juania1-1529573** [comment]
Cancel button referring to the cancel button on the form.

**Comment by abegel** [comment]
This is definitely a UI bug in my book.
