### ISSUE TITLE
Unable to add event after signing in

### ISSUE THREAD

**Issue by harshivcodes** [breakbreakdown/webapp#7]
I am unable to add an event on the app. Sometimes, clicking on the add event button prompts to sign in with google again. I made sure to enable Javascript and disable popups. Here's a screenshot of the developer console if it's any help.

![image](https://user-images.githubusercontent.com/24836340/40899293-103135f8-677b-11e8-894a-afd3a6e4d4eb.png)

**Comment by juania1-1529573** [comment]
Duplicate; out error was that if someone had a task in their day then it wouldn't push to firebase. Should be fixed by 5pm. Thanks!
