### ISSUE TITLE
Adding tasks on days that have already passed

### ISSUE THREAD

**Issue by janequichocho** [breakbreakdown/webapp#9]
Reproduction steps:
1. Log in
2. Click on the plus icon in "Add Event" section
3. Change setting from event to task
4. Enter in the following fields
    - Title: Book report
    - Date: 2018-06-01 
    - Hours: 2
    - Minutes: 15
    - Location: Library
5. Click on Add to Calendar button

I get an alert saying I've successfully added the task to my calendar, but the date I've entered has already passed. Since the app only shows your free time for the current day, it wouldn't be able to show my free time for the date I entered a task into.

**Comment by juania1-1529573** [comment]
Our application is only a single day view of your schedule. We still give our users the option of adding an event to their google calendar.
